- .commit-template.txt
Issue Resolved: #26
- close #26 
커밋 탬플릿 문서 추가
- 로컬에서 `git config --local commit.template ".commit-template.txt"` 명령 필요
> 📝 docs: 커밋 탬플릿 추가

- back/src/app.module.ts
- close #61 
`MOCK_MODE` 환경 변수가 `true`일 때에 활성화되며, mock 모듈 외의 모듈을 app.module에서 임포트하지 않음.
> 백엔드 Mock 모드 실행 지원

- back/src/domains/reservation/controller/reservation.controller.ts
- back/src/domains/reservation/dto/reservationSepecificDto.ts
- back/src/domains/reservation/repository/reservation.repository.ts
- back/src/domains/reservation/reservation.module.ts
- back/src/domains/reservation/service/reservation.service.ts
- 유저의 예매 내역 조회
- 예매 내역은 현 시간 이후 예매 내역만을 제공
Issue Resolved: #99
- close #99 
- 유저의 예매 내역 조회
- /reservation [GET] 요청 처리
- 현 시간 이후 시작하는 이벤트에 대해서만 예매 내용 제공
> ✨ feat: 유저의 예매 내역 조회

- back/src/config/setupSwagger.ts
- swagger 페이지에서 인증 기능 추가
- 인증 시에 입력한 쿠키 값을 SID로 설정해서 전송 Issue Resolved: #131
- close #131 
- 사용법
- https://chestnut-sense-efd.notion.site/Swagger-API-fbf94aac52ea4afa9a0ada8016ff6a83?pvs=4
> ✨ feat: swagger-api 인증 및 쿠키 유지

- back/src/domains/booking/const/seatsBroadcastInterval.const.ts
- back/src/domains/booking/const/seatsSseRetryTime.const.ts
- back/src/domains/booking/luaScripts/getSeatsLua.ts
- back/src/domains/booking/service/booking-seats.service.ts
- close #161 
- SSE 연결마다 새 Observable 객체가 생성되지 않도록 함.
- 이벤트마다 Subject 객체가 하나씩 생성되어 이로부터 여러 클라이언트에게 브로드캐스트하는 기능 구현
> SSE 브로드캐스트 리팩토링

- back/src/domains/booking/service/open-booking.service.ts
- back/src/domains/place/entity/section.entity.ts
- close #183 
- RDB에 Section.seats가 `string[]`으로 저장된다 가정하고 있던 로직을 `boolean[]`으로 변경함.
> RDB에 Section.seats 저장 타입 일치 문제

- back/src/domains/booking/const/inBookingDefaultMaxSize.const.ts
- back/src/domains/booking/const/inBookingPoolSize.const.ts
- back/src/domains/booking/controller/booking.controller.ts
- back/src/domains/booking/dto/inBookingSizeReq.dto.ts
- back/src/domains/booking/dto/inBookingSizeRes.dto.ts
- back/src/domains/booking/service/booking.service.ts
- back/src/domains/booking/service/in-booking.service.ts
- back/src/domains/booking/service/open-booking.service.ts
- back/src/domains/booking/service/waiting-queue.service.ts
- close #197
- 예매가 열려 있는 특정 이벤트에 대해 좌석 선택 페이지 입장 가능 인원 수를 설정하는 관리자용 API 구현
- 예매가 열려 있는 모든 이벤트에 대해 좌석 선택 페이지 입장 가능 인원 수를 설정하는 관리자용 API 구현
> 관리자 기능: 좌석 선택 페이지 입장 가능 인원 조정

- back/src/domains/reservation/service/reservation.service.ts
- 예약 확정 요청에서 secionid를 참조하던 부분을 secionIndex를 참조하도록 변경 Issue Resolved: #
- close #200
- 예매 확정 요청에서 보내주는 secionIndex를 sectionId를 참조하는것으로 착각했습니다. 이부분을 수정해서 secionIndex를 참조하도록 변경했습니다.
> 좌석 예매 secion_id 참조를 section_index참조하도록 변경

- back/src/auth/guard/session.guard.ts
- back/src/auth/service/auth.service.ts
- back/src/domains/user/controller/user.controller.ts
- back/src/domains/user/service/user.service.ts
- close #202 
- 기존 redis에 key는 user:${sid}  value에는 {userid, loginid, role}등을 정보를 저장하는 구조이고 중복로그인을 대처하지 못했던 문제가 있었습니다.
- 중복 로그인을 방지하기위해서 sessio에 적합한 방식을 찾다 redis에 login한 user의 id를 하나 더 저장해서 운영하는 방식을 사용했습니다.
- 로그인 시 총 두개의 key-value가redis에 등록됩니다. 
- 하나는 위에서 설명한   key는 user:${sid}  value에는 {userid, loginid, role}등을 정보를 저장하는 key-value쌍
- 다른 하나는 key user-id:{loginid} value는 sid 값을 가지는 key-value쌍입니다.
- 이 두개의 쌍을 이용해서 로그인 요청시 user-id:${login요청을 보낸 유저의 loginID}가 있는지 확인 후 없다면 위에서 언급한 두개의 key-value쌍을 redis에 등록합니다.
- 만약 로그인한 유저가 있다면 로그인 처리를 하고 이 값을 갱신하도록 합니다.
-  위과정을 통해서 중복 로그인 방지 로직을 추가했습니다.
> 중복 로그인 방지로직

- back/src/domains/booking/service/in-booking.service.ts
- back/src/domains/reservation/service/reservation.service.ts
- 예매 요청으로 들어온 좌석과 redis session속 bookedSeats 좌석이 동일한지 확인하는 로직 추가 Issue Resolved: #
- close #206 
- 좌석 확정 시 좌석 선택 페이지에서 선점한 좌석과 예매 확정요청으로 보낸 좌석 데이터가 동일한지 확인하는 로직을 추가했습니다.
- 다를경우 또는 없는 좌석을 신청할 경우 예외가 발생되고 클라이언트로는 stats400에 예매가 실패했다는 응답을 보내도록 했습니다.
> 좌석 확정 시 선점한 좌석과 예약하는 좌석과 비교하는 로직

- back/src/domains/booking/service/open-booking.service.ts
- close #214 
- 이벤트의 좌석 선택 페이지 입장 인원 수 설정 로직보다, 좌석 선택 페이지 기본 최대 인원 수 설정이 먼저 행해지도록 순서 변경
> 좌석 선택 페이지 기본 최대 인원 수 설정 문제

- back/src/domains/booking/controller/booking.controller.ts
- back/src/domains/booking/service/in-booking.service.ts
- close #217 
이벤트가 새로 오픈될 때 참조할, 좌석 선택 페이지의 기본 사이즈를 설정하는 API
> 관리자 기능: 좌석 선택 페이지 기본 사이즈 설정

- back/src/auth/service/auth.service.ts
- back/src/domains/booking/booking.module.ts
- back/src/domains/booking/service/booking-seats.service.ts
- back/src/domains/booking/service/booking.service.ts
- back/src/domains/booking/service/in-booking.service.ts
- back/src/domains/booking/service/waiting-queue.service.ts
- back/src/domains/reservation/reservation.module.ts
- back/src/domains/reservation/service/reservation.service.ts
- back/src/domains/user/service/user.service.ts
- close #219
- AuthSercie속 set/getEventTarget함수는 Auth와는 상관없는 로직이라고 판단했습니다. 이를 User도메인속 UseService로 옮겼습니다.
- 옮기면서 발생하는 문제를 해결하기위해 UserModule import하고, UserServcice에서 set/getEventTarget를 사용하도록 변경했습니다.
> AuthService 속 함수들 책임 분리

- back/src/domains/reservation/service/reservation.service.ts
- close #224
- 예약 내역에서 createdAt이 한국시간으로 안되는 버그가 있었는데 이를 해결했습니다.
> 예약 확정 createdAt 한국 시간 출력되도록 변경

- back/src/domains/booking/service/waiting-queue.service.ts
- close #231 
- head 대기자를 불러왔을 때 결과가 없다면 '다음 발급될 번호표 순서'를 대신 반환하여 해결
> 대기 큐: 대기자가 없을 때 headOrder null반환 문제

- back/src/domains/booking/service/booking.service.ts
- back/src/domains/booking/service/in-booking.service.ts
- back/src/domains/reservation/service/reservation.service.ts
- close #234 
- InBooking 세션에 `saved` 필드 추가
- 예매 확정 요청이 받아들여진 경우에 `saved` 필드가 `true`로 설정
- 좌석 선택 중 이탈 시, `saved`가 `true`가 아니라면 모든 `bookedSeats`를 회수
> 좌석 선택 중 이탈 시 좌석 회수

- back/src/domains/booking/controller/booking.controller.ts
- back/src/domains/booking/service/open-booking.service.ts
- close #211 
- 관리자 계정용 API: 오픈 대상에 해당하는 이벤트를 다시 탐색하여 오픈한다.
> 관리자 기능: 이벤트 오픈 스케줄 리프레시

- back/src/domains/booking/controller/booking.controller.ts
- back/src/domains/booking/service/in-booking.service.ts
- back/src/domains/booking/service/open-booking.service.ts
- close #233 
- 특정 이벤트에 대해 강제 마감 작업 진행
- 해당 이벤트에 대해 다시 오픈 스케줄링을 함(오픈 시간 이후라면 즉시 오픈, 아니라면 스케줄에 등록)
> 관리자 기능: 오픈된 이벤트 상태 초기화

- back/src/domains/booking/booking.module.ts
- back/src/domains/booking/service/booking.service.ts
- back/src/domains/reservation/repository/reservation.repository.ts
- back/src/domains/reservation/service/reservation.service.ts
- close #254
- 예매 내역 삭제 시 좌석을 반납하여, 예약이 마감되지 않은 경우에 다른 유저가 자리를 가져갈 수 있도록 함
> 예매 내역 삭제 시 좌석 반납

- back/src/domains/booking/service/open-booking.service.ts
- close #260 
- open-booking 서비스에서 resetUserStatus를 호출할 때, 리셋할 세션이 redis에 존재하는 지 확인하고 실행되도록 변경함.
> 없어진 유저에 대한 상태 초기화 시 에러

- back/src/domains/booking/const/sseMaximumInterval.ts
- back/src/domains/booking/service/booking-seats.service.ts
- back/src/domains/booking/service/waiting-queue.service.ts
- close #269 
- 최대 SSE 발행 주기를 설정하는 상수 구현
- 모든 SSE가 '최대 SSE 발행 주기'를 넘는 주기를 갖지 않도록 적용
- 좌석 현황 SSE의 경우, '최대 SSE 발행 주기'마다 변경 사항이 없더라도 좌석 현황을 발행하도록 변경
> SSE 연결에서 하트비트 메시지 송신

- back/src/domains/reservation/entity/reservedSeat.entity.ts
- back/src/domains/reservation/repository/reservation.repository.ts
- back/src/domains/reservation/repository/reservedSeat.repository.ts
- close #281 
- Reservation이 삭제될 때, 관련된 Reserved_Seat도 삭제되도록 변경 Issue Resolved: #281
> ✨ feat: Reserved_Seat의 soft delete 적용

- back/src/domains/program/service/program.service.ts
- close #287 
- 예매 가능 시간이 지난 이벤트는 프로그램 조회시 제공하지 않음 Issue Resolved: #287
> 🐛 fix: 예매 가능 시간이 지난 이벤트는 서빙하지 않도록 수정

- front/src/pages/WaitingQueuePage/index.tsx
- close #291
- 대기 큐 페이지에서 canGo가 한차례씩 늦게 true가 되는 오류 수정
> 대기 큐 입장 조건 판단 오류 수정
