back/package-lock.json
back/package.json
back/src/app.module.ts
back/src/dto/userCreate.dto.ts
back/src/entity/user.entity.ts
back/src/user/user.controller.spec.ts
back/src/user/user.controller.ts
back/src/user/user.repository.ts
back/src/user/user.service.spec.ts
back/src/user/user.service.ts

- UserController 추가
- UserService 추가
- UserRepository 추가
- CreateUserDto 추가
- UserEntity 추가
- close #15 
- user Layer추가
- typeORM, Mysql 의존성 추가

userlayer 추가

---

back/package-lock.json
back/package.json
back/src/app.module.ts
back/src/place/place.module.ts
back/src/place/place.service.spec.ts
back/src/place/place.service.ts
back/src/program/entities/program.entity.ts
back/src/program/program.controller.spec.ts
back/src/program/program.controller.ts
back/src/program/program.module.ts
back/src/program/program.service.spec.ts
back/src/program/program.service.ts
back/src/reservation/reservation.controller.spec.ts
back/src/reservation/reservation.controller.ts
back/src/reservation/reservation.module.ts
back/src/reservation/reservation.service.spec.ts
back/src/reservation/reservation.service.ts
back/src/util/util.controller.spec.ts
back/src/util/util.controller.ts
back/src/util/util.module.ts
back/src/util/util.service.spec.ts
back/src/util/util.service.ts

도메인 별 디렉토리 생성

---

back/src/app.module.ts

- close #48 
[Modules | NestJS - A progressive Node.js framework](https://docs.nestjs.com/modules)

app.module 불필요 의존성 제거

---

back/src/domains/user/repository/user.repository.ts
back/src/domains/user/service/user.service.ts

- close #63 
- UserEntity 변경에따른 회원가입 안되는 문제 해결

회원가입 에러 해결

---

back/package-lock.json
back/package.json
back/src/main.ts
package-lock.json
package.json

- /package.json에 있는 백엔드 의존성 삭제
- /back/package.json에 루트 디렉토리에서 삭제한 의존성 설치
- /back/main.ts에 있는 사용하지 않는 임포트문 삭제 Issue Resolved: #
- close #이슈번호

🐛 fix: npm 의존성 위치 변경

---

back/src/util/user-injection/user.decorator.service.ts

- User 데코레이터를 통한 유저 객체 주입시 UserParamDto가 주입되도록 수정 Issue Resolved: #23
- close #23

💩 chore: 유저 객체 주입 클래스 변경

---

back/package-lock.json
back/package.json

- close #83 
- commonJS를 지원하는 버전으로 하향 설치하여 문제 해결

'camelcase-keys' 패키지 임포트 에러

---

back/src/domains/booking/booking.module.ts
back/src/domains/booking/const/bookingAmount.const.ts
back/src/domains/booking/controller/booking.controller.ts
back/src/domains/booking/dto/bookingAmountReqDto.ts
back/src/domains/booking/dto/bookingAmountResDto.ts
back/src/domains/booking/service/in-booking.service.ts

- close #82 
- 예매 최소/최대 매수 상수 구현
- 요청/응답 전용 Dto 구현
- API 구현

예매 매수 설정 API

---

front/index.html
front/package.json
front/src/hooks/useForm.tsx
front/src/layout/Layout.tsx
front/src/pages/SignInPage.tsx
front/src/pages/SignUpPage.tsx
front/src/routes/index.tsx

- close #37 
- 로그인 페이지 
- 회원가입 페이지 
- admin(x)
- api 연결(x)

로그인 회원가입 페이지

---

front/src/App.tsx
front/src/components/common/Navbar.tsx
front/src/components/common/Skeleton.tsx
front/src/layout/Layout.tsx
front/src/pages/MainPage.tsx
front/src/pages/ProgramsPage.tsx
front/src/routes/index.tsx

- close #92 
- 프로그램 선택 페이지 레이아웃(api 없이 mock data 이용, 이미지는 랜덤 이미지)

프로그램 선택 페이지

---

back/package-lock.json
back/package.json
back/src/app.module.ts
back/src/domains/booking/booking.module.ts
back/src/domains/booking/controller/booking.controller.ts
back/src/domains/booking/service/booking-seats.service.ts
back/src/domains/booking/service/open-booking.service.ts
back/src/domains/event/repository/event.reposiotry.ts
back/src/domains/place/place.module.ts
back/src/domains/place/repository/section.repository.ts

- close #45
- 실시간 좌석 현황 구독(SSE) API 구현
- 실시간 좌석 관리 서비스 구현
- 예매 자동 오픈 서비스 구현
실시간 좌석 현황을 Redis에 저장하여 참조한다. 현재 트랜잭션 관리 처리가 하나도 되지 않은 상태이다.

좌석 변경 사항을 SSE를 통해 제공

---

back/src/domains/user/controller/user.controller.ts
back/src/domains/user/dto/userCreate.dto.ts
back/src/domains/user/dto/userLogin.dto.ts
back/src/domains/user/service/user.service.ts

- close #125 
- signin API를 loginAPI로변경
- 로그인 함수에서 예외 반화 로직 변경

로그인 로직 리팩토링

---

back/src/config/setupSwagger.ts

- swagger 페이지에서 인증 기능 추가
- 인증 시에 입력한 쿠키 값을 SID로 설정해서 전송 Issue Resolved: #131
- close #131 
- swagger를 통해 관리자로 접속하는 방식은 아래를 참고
- https://chestnut-sense-efd.notion.site/Swagger-API-fbf94aac52ea4afa9a0ada8016ff6a83?pvs=4

✨ feat: swagger-api 인증 및 쿠키 유지

---

back/src/domains/event/controller/event.controller.ts
back/src/domains/place/controller/place.controller.ts
back/src/domains/program/controller/program.controller.ts

feat: 인증 및 인가 확인이 필요한 url에 데코레이터 지정
- close #135 
-프로그램 생성 및 삭제 관리자 권한 데코레이터 추가
-장소 생성 및 삭제 관리자 권한 데코레이터 추가
-섹션 추가 관리자 권한 데코레이터 추가
-이벤트 조회 인증 데코테이터 추가
-이벤트 생성 및 삭제 관리자 권한 데코레이터 추가

✨ feat: 인증 및 인가 확인이 필요한 url에 데코레이터 지정

---

back/src/domains/booking/dto/serverTime.dto.ts
back/src/domains/event/dto/eventSpecificDto.ts
back/src/domains/event/dto/placeSpecificEventDto.ts
back/src/domains/place/dto/layout.dto.ts
back/src/domains/place/dto/seatInfo.dto.ts
back/src/domains/program/dto/eventSpecificProgramDto.ts
back/src/domains/program/dto/placeMainPageDto.ts
back/src/domains/program/dto/placeSpecificProgramDto.ts
back/src/domains/program/dto/programMainPageDto.ts
back/src/domains/program/dto/programSpecificDto.ts
back/src/domains/reservation/dto/reservationCreateDto.ts
back/src/domains/reservation/dto/reservationResultDto.ts
back/src/domains/reservation/dto/reservationSeatInfoDto.ts
back/src/domains/reservation/dto/reservationSepecificDto.ts
back/src/domains/user/controller/user.controller.ts
back/src/domains/user/dto/userCreate.dto.ts
back/src/domains/user/dto/userLogin.dto.ts
back/src/domains/user/dto/userLoginIdCheck.dto.ts
back/src/main.ts

Issue Resolved: #127 
- close #127 
- 통신에 사용되는 DTO에 @Apioperation 데코레이터로 설명 추가

✨ feat: DTO에 ApiOperation 데코레이터 추가

---

front/src/api/axios.ts
front/src/api/user.ts
front/src/constants/index.ts
front/src/pages/LoginPage.tsx
front/src/pages/SignUpPage.tsx
front/src/routes/index.tsx

- close #139 
- 카멜케이스가 저용되면서 타입변경 및 타입제거
- 기존 interceptor 변환기 제거

api 카멜 케이스 변경 적용

---

back/src/domains/place/controller/place.controller.ts
back/src/domains/place/repository/section.repository.ts
back/src/domains/place/service/place.service.ts

- close #143 
- place.sections에 저장된 아이디를 통해 섹션을 조회하도록 수정 Issue Resolved: #143

🐛 fix: 섹션 데이터 조회 로직 수정

---

back/src/domains/place/service/place.service.ts

Issue Resolved: #145
- close #145 
overview 정보 추가

좌석 정보에 overview정보추가

---

back/src/domains/place/dto/layout.dto.ts

♻️ refactor: laㅛout dto 추가

---

back/src/config/typeOrmConfig.ts

- close #150 
- charset을 utf8mb4로 설정
- timezone을 z로 설정 Issue Resolved: #150

✨ feat: typeorm 설정 추가

---

back/src/domains/booking/service/booking.service.ts
back/src/domains/event/dto/eventDto.ts
back/src/domains/event/repository/event.reposiotry.ts
back/src/domains/event/service/event.service.ts
back/src/domains/program/repository/program.repository.ts

- close #154 
- 이벤트 상세 조회 쿼리 최적화
- 이벤트 추가 쿼리 최적화
- OpenBookingService.checkAndOpenReservations에서 조회하는 event DTO 분리
- event 관련 정보만 담은 dto 생성

♻️ refactor: 이벤트 관련 쿼리 최적화

---

back/src/domains/reservation/repository/reservation.repository.ts
back/src/domains/reservation/service/reservation.service.ts

- close #152 
- 예약 내역 조회 쿼리 최적화 Issue Resolved: #152

♻️ refactor: 예약 내역 조회 쿼리 최적화

---

back/src/auth/guard/session.guard.ts
back/src/domains/event/repository/event.reposiotry.ts
back/src/domains/place/repository/section.repository.ts
back/src/domains/reservation/controller/reservation.controller.ts
back/src/domains/reservation/dto/reservationCreateDto.ts
back/src/domains/reservation/dto/reservationDataDto.ts
back/src/domains/reservation/dto/reservationSeatInfoDto.ts
back/src/domains/reservation/repository/reservedSeat.repository.ts
back/src/domains/reservation/reservation.module.ts
back/src/domains/reservation/service/reservation.service.ts
back/src/domains/user/service/user.service.ts

- close #128 
- Lazy 로딩으로 인하 N+1 문제 해결 위해 부분적으로 eager 로딩 사용
- 디버깅용 console.log 제거
- swagger 예시 수정

좌석 확정 API 로직변경

---

front/nginx/nginx.conf

- close #173 
- 정적 파일 서빙을 위한 nginx 설정 파일 Issue Resolved: #173

✨ feat: 정적 파일 서빙을 위한 nginx 설정 파일

---

back/src/domains/event/entity/event.entity.ts
back/src/domains/reservation/entity/reservedSeat.entity.ts
back/src/domains/reservation/service/reservation.service.ts

- close #170 
- Reserved_Seat Entity에서 Event 참조하도록 Entity를 수정
- 같은 이벤트에 대해서 중복된 좌석을 예매할 수 없도록 로직 추가
- 존재하지 않는 좌석에 대한 요청은 400 코드 반환하도록 로직 추가

예매 확정 기능 검증 로직 추가 

---

front/src/api/axios.ts
front/src/api/reservation.ts
front/src/components/common/Field.tsx
front/src/constants/index.ts
front/src/hooks/useFieldContext.tsx

- close #177 
- 기존에 있던 대소문자 타입 에러 수정, tsc로 파일 전체 타입 에러 확인
- api 상수 변경
- 배포 환경에서는  api url 앞에 '/api'가 들어가도록 수정 
-navbar  api 상수 적용

navbar 에러 수정

---

back/src/domains/booking/luaScripts/getSeatsLua.ts
back/src/domains/booking/service/booking-seats.service.ts

- close #179 
좌석 현황이 정상적으로 읽히지 않은 경우를 판별해 InternalServerError를 발생시킴.

좌석 현황 읽기 예외 처리

---

back/src/domains/booking/service/waiting-queue.service.ts

- close #181 
대기 큐에 대기 중인 인원이 없을 때에는 좌석 선택 페이지에 여석이 생겨도 큐에서 pop하지 않도록 함.

대기 큐에 대기 중인 인원이 없을 때에도 pop하는 문제

---

back/src/domains/booking/controller/booking.controller.ts
back/src/domains/place/controller/place.controller.ts
back/src/mock/event/event.controller.ts
back/src/mock/place/place.controller.ts
back/src/mock/program/program.controller.ts

- API 네이밍 복수형인것들은 단수형으로 변형 Issue Resolved: #
- close #184
- API네이밍 복수형인것들은 단수형으로 변경

♻️ refactor: API 네이밍 적용

---

back/src/auth/guard/session.guard.ts
back/src/auth/service/auth.service.ts
back/src/domains/user/service/user.service.ts

인증 및 인가 리팩토링

---

back/src/domains/reservation/repository/reservation.repository.ts

- close #203
- 예매 취소 레포지토리 로직 수정 Issue Resolved: #203

🐛 fix: 예매 취소 레포지토리 로직 수정

---

back/src/domains/booking/service/open-booking.service.ts

- close #213 
예매 오픈 스케줄링을 리프레시할 때, 열려 있는 이벤트를 건너뛰도록 조치

예매 오픈 스케줄링 시 기존 이벤트 초기화 문제

---

back/src/auth/service/auth.service.ts
back/src/domains/user/service/user.service.ts
back/src/util/user-injection/user.decorator.service.ts
back/src/util/user-injection/userParamDto.ts

- close #221 
- 유저 주입 시에 MySQL 접근하지 않도록 설정
- 유저 주입 시에 비밀번호는 주입하지 않도록 변경

♻️ refactor: 유저 주입 데코레이터 최적화

---

front/package-lock.json
front/package.json
front/src/App.tsx
front/src/api/axios.ts
front/src/components/Captcha/index.tsx
front/src/components/Navbar/index.tsx
front/src/components/Toast/Toast.tsx
front/src/components/Toast/ToastContainer.tsx
front/src/components/common/Popover.tsx
front/src/components/loaders/WithLogin.tsx
front/src/components/loaders/WithoutLogin.tsx
front/src/layout/Layout.tsx
front/src/pages/LoginPage/index.tsx
front/src/pages/NotFoundPage.tsx
front/src/pages/ReservationPage/SectionAndSeat.tsx
front/src/pages/ReservationPage/index.tsx
front/src/pages/ReservationWaitingPage/index.tsx
front/src/pages/SignupPage/index.tsx

- close #226 
- 토스트 추가 
-  좌석 선택/ 취소시 토스트 추가
- 좌석 api 실패시 토스트 추가
- 예매내역 삭제 성공, 실패시 토스트 추가
- 예매 확정시 navbar 리렌더링
- 로그인 실패시 리다이렉트 x
- navbar 크기 유지 및 레이아웃 유지, 스크롤 에러 수정 
- 회원가입, 로그인 등 navbar 위로 올라가는 에러 수정
- 로그아웃 메인페이지 라우팅

레이아웃 및 api 최적화

---

back/src/domains/user/controller/user.controller.ts
back/src/domains/user/entity/user.entity.ts
back/src/domains/user/service/user.service.ts

- close #236 
- [GET] /user/guest로 요청이 들어오면 일회용으로 용할 수 있는 Geust세션을 만들어서 기능을 이용할 수 있도록 해주기

Guest모드 추가

---

back/src/domains/booking/service/booking.service.ts
back/src/domains/booking/service/in-booking.service.ts

- close #240 
- InBooking 상태에서 bookingAmount를 변경하면 해당 세션이 갖고 있는 모든 좌석을 반납함

예매 매수 변경 시 선점한 좌석들 반납

---

.github/workflows/ci.yml

- close #244
- CICD를 위한 yml파일 작성 Issue Resolved: #244

✨ feat: cicd를 위한 yml파일

---

front/package-lock.json
front/package.json
front/src/App.tsx
front/src/api/user.ts
front/src/components/Confirm/ConfirmContainer.tsx
front/src/components/Navbar/index.tsx
front/src/components/common/Popover.tsx
front/src/components/loaders/WithLogin.tsx
front/src/components/loaders/WithoutLogin.tsx
front/src/constants/index.ts
front/src/hooks/useConfirm.tsx
front/src/hooks/usePreventLeave.tsx
front/src/pages/ReservationPage/SeatMap.tsx
front/src/pages/ReservationPage/SectionAndSeat.tsx
front/src/pages/ReservationPage/index.tsx
front/src/providers/ConfirmProvider.tsx
front/src/type/user.ts
front/src/utils/debounce.ts

- close #250 
- 게스트 기능 추가
- confirm 컴포넌트 추가
- 좌석 개수 변경 기능 추가
- 이탈 방지 기능 추가

게스트 기능 및 좌석 개수 변경, 이탈 방지 기능 추가 

---

back/src/domains/user/entity/user.entity.ts

- guest는 패스워드가 필요없으므로 password를 nullable로 변경
- is_guest default값을 0(false)로 변경 Issue Resolved: #
- close #257 
- User Entity 옵션을 변경
- login_password는 nullable하게 변경
- is_guest는 defalut가 false로 변경

♻️ refactor: UserEntity option 변경

---

back/src/domains/user/entity/user.entity.ts

userEnity 변경 적용

---

back/src/domains/event/dto/eventSpecific.dto.ts
back/src/domains/event/service/event.service.ts

- close #261 
- 이벤트 가격 정보 추가 Issue Resolved: #261

💩 chore: 이벤트 가격 정보 추가

---

back/src/domains/reservation/entity/reservedSeat.entity.ts
back/src/domains/reservation/service/reservation.service.ts

- close #265
- 불가피하게 reservedSeat 테이블을 수정함.(col-len, section-index 필요)
- 좌석 위치 계산을 알맞게 수정함

예매 취소 시 잘못된 좌석 인덱스 설정으로 인해 안되는 에러

---

front/src/components/Navbar/index.tsx
front/src/components/common/Loading.tsx
front/src/components/loaders/WithLogin.tsx
front/src/hooks/usePreventLeave.tsx
front/src/pages/ReservationPage/SeatMap.tsx
front/src/pages/ReservationPage/SectionAndSeat.tsx
front/src/pages/WaitingQueuePage/index.tsx

- close #266 
- 좌석 변경시 로딩 
- 클릭 방지
- toast 중복 방지

좌석 변경시 로딩 처리

---

front/src/pages/WaitingQueuePage/index.tsx

입장 flag 계산식 변경

---

front/src/type/index.ts

💩 chore: 타입 추가

---

front/src/components/loaders/WithoutLogin.tsx
front/src/pages/ProgramsPage/ProgramCard.tsx
front/src/pages/ProgramsPage/index.tsx

page 배열 및 포스터 크기 고정

---

back/src/domains/booking/service/open-booking.service.ts

- close #285
- 정각 1분 전에 실행되는 스케줄링에 try, catch문으로 에러 로깅을 한다.

정기적 오픈 스케줄링 시 에러 캐치 및 로깅
